version : '3.8'

services:
  grafana:
      image: grafana/grafana:latest
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin
      volumes:
        - grafana-storage:/var/lib/grafana
      restart: always
      networks:
        - airflow_default

networks:
  airflow_default:
    external: true 


volumes:
  grafana-storage:
 
